/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PreviewRelatoriosRouteImport } from './routes/preview-relatorios'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvGerencialRouteImport } from './routes/tv.gerencial'
import { Route as TvDashboardRouteImport } from './routes/tv.dashboard'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTriagemRouteImport } from './routes/_authenticated/triagem'
import { Route as AuthenticatedTransferenciasLoteRouteImport } from './routes/_authenticated/transferencias-lote'
import { Route as AuthenticatedTransferenciasRouteImport } from './routes/_authenticated/transferencias'
import { Route as AuthenticatedRecebimentoRouteImport } from './routes/_authenticated/recebimento'
import { Route as AuthenticatedInventarioCentralRouteImport } from './routes/_authenticated/inventario-central'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedIntegracaoMeliRouteImport } from './routes/_authenticated/integracao-meli'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedGerencialRouteImport } from './routes/_authenticated/gerencial'
import { Route as AuthenticatedDevolucoesRouteImport } from './routes/_authenticated/devolucoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContagemRouteImport } from './routes/_authenticated/contagem'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBasesRouteImport } from './routes/_authenticated/bases'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as ApiPublicMeliImportarRotaBrutaRouteImport } from './routes/api/public/meli/importar-rota-bruta'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRelatoriosRoute = PreviewRelatoriosRouteImport.update({
  id: '/preview-relatorios',
  path: '/preview-relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvGerencialRoute = TvGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => TvRoute,
} as any)
const TvDashboardRoute = TvDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TvRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTriagemRoute = AuthenticatedTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransferenciasLoteRoute =
  AuthenticatedTransferenciasLoteRouteImport.update({
    id: '/transferencias-lote',
    path: '/transferencias-lote',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransferenciasRoute =
  AuthenticatedTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecebimentoRoute =
  AuthenticatedRecebimentoRouteImport.update({
    id: '/recebimento',
    path: '/recebimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioCentralRoute =
  AuthenticatedInventarioCentralRouteImport.update({
    id: '/inventario-central',
    path: '/inventario-central',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracaoMeliRoute =
  AuthenticatedIntegracaoMeliRouteImport.update({
    id: '/integracao-meli',
    path: '/integracao-meli',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerencialRoute = AuthenticatedGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevolucoesRoute = AuthenticatedDevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContagemRoute = AuthenticatedContagemRouteImport.update({
  id: '/contagem',
  path: '/contagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBasesRoute = AuthenticatedBasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMeliImportarRotaBrutaRoute =
  ApiPublicMeliImportarRotaBrutaRouteImport.update({
    id: '/api/public/meli/importar-rota-bruta',
    path: '/api/public/meli/importar-rota-bruta',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/preview-relatorios': typeof PreviewRelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tv': typeof TvRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/bases': typeof AuthenticatedBasesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contagem': typeof AuthenticatedContagemRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/gerencial': typeof AuthenticatedGerencialRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/integracao-meli': typeof AuthenticatedIntegracaoMeliRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/inventario-central': typeof AuthenticatedInventarioCentralRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/transferencias-lote': typeof AuthenticatedTransferenciasLoteRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/tv/dashboard': typeof TvDashboardRoute
  '/tv/gerencial': typeof TvGerencialRoute
  '/api/public/meli/importar-rota-bruta': typeof ApiPublicMeliImportarRotaBrutaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/preview-relatorios': typeof PreviewRelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tv': typeof TvRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/bases': typeof AuthenticatedBasesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contagem': typeof AuthenticatedContagemRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/gerencial': typeof AuthenticatedGerencialRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/integracao-meli': typeof AuthenticatedIntegracaoMeliRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/inventario-central': typeof AuthenticatedInventarioCentralRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/transferencias-lote': typeof AuthenticatedTransferenciasLoteRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/tv/dashboard': typeof TvDashboardRoute
  '/tv/gerencial': typeof TvGerencialRoute
  '/api/public/meli/importar-rota-bruta': typeof ApiPublicMeliImportarRotaBrutaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/preview-relatorios': typeof PreviewRelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tv': typeof TvRouteWithChildren
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/bases': typeof AuthenticatedBasesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contagem': typeof AuthenticatedContagemRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/_authenticated/gerencial': typeof AuthenticatedGerencialRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/integracao-meli': typeof AuthenticatedIntegracaoMeliRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/inventario-central': typeof AuthenticatedInventarioCentralRoute
  '/_authenticated/recebimento': typeof AuthenticatedRecebimentoRoute
  '/_authenticated/transferencias': typeof AuthenticatedTransferenciasRoute
  '/_authenticated/transferencias-lote': typeof AuthenticatedTransferenciasLoteRoute
  '/_authenticated/triagem': typeof AuthenticatedTriagemRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/tv/dashboard': typeof TvDashboardRoute
  '/tv/gerencial': typeof TvGerencialRoute
  '/api/public/meli/importar-rota-bruta': typeof ApiPublicMeliImportarRotaBrutaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/preview-relatorios'
    | '/reset-password'
    | '/tv'
    | '/auditoria'
    | '/bases'
    | '/configuracoes'
    | '/contagem'
    | '/dashboard'
    | '/devolucoes'
    | '/gerencial'
    | '/historico'
    | '/inicio'
    | '/integracao-meli'
    | '/inventario'
    | '/inventario-central'
    | '/recebimento'
    | '/transferencias'
    | '/transferencias-lote'
    | '/triagem'
    | '/usuarios'
    | '/tv/dashboard'
    | '/tv/gerencial'
    | '/api/public/meli/importar-rota-bruta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/preview-relatorios'
    | '/reset-password'
    | '/tv'
    | '/auditoria'
    | '/bases'
    | '/configuracoes'
    | '/contagem'
    | '/dashboard'
    | '/devolucoes'
    | '/gerencial'
    | '/historico'
    | '/inicio'
    | '/integracao-meli'
    | '/inventario'
    | '/inventario-central'
    | '/recebimento'
    | '/transferencias'
    | '/transferencias-lote'
    | '/triagem'
    | '/usuarios'
    | '/tv/dashboard'
    | '/tv/gerencial'
    | '/api/public/meli/importar-rota-bruta'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/preview-relatorios'
    | '/reset-password'
    | '/tv'
    | '/_authenticated/auditoria'
    | '/_authenticated/bases'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contagem'
    | '/_authenticated/dashboard'
    | '/_authenticated/devolucoes'
    | '/_authenticated/gerencial'
    | '/_authenticated/historico'
    | '/_authenticated/inicio'
    | '/_authenticated/integracao-meli'
    | '/_authenticated/inventario'
    | '/_authenticated/inventario-central'
    | '/_authenticated/recebimento'
    | '/_authenticated/transferencias'
    | '/_authenticated/transferencias-lote'
    | '/_authenticated/triagem'
    | '/_authenticated/usuarios'
    | '/tv/dashboard'
    | '/tv/gerencial'
    | '/api/public/meli/importar-rota-bruta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PreviewRelatoriosRoute: typeof PreviewRelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TvRoute: typeof TvRouteWithChildren
  ApiPublicMeliImportarRotaBrutaRoute: typeof ApiPublicMeliImportarRotaBrutaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-relatorios': {
      id: '/preview-relatorios'
      path: '/preview-relatorios'
      fullPath: '/preview-relatorios'
      preLoaderRoute: typeof PreviewRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/gerencial': {
      id: '/tv/gerencial'
      path: '/gerencial'
      fullPath: '/tv/gerencial'
      preLoaderRoute: typeof TvGerencialRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/dashboard': {
      id: '/tv/dashboard'
      path: '/dashboard'
      fullPath: '/tv/dashboard'
      preLoaderRoute: typeof TvDashboardRouteImport
      parentRoute: typeof TvRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/triagem': {
      id: '/_authenticated/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AuthenticatedTriagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencias-lote': {
      id: '/_authenticated/transferencias-lote'
      path: '/transferencias-lote'
      fullPath: '/transferencias-lote'
      preLoaderRoute: typeof AuthenticatedTransferenciasLoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencias': {
      id: '/_authenticated/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof AuthenticatedTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recebimento': {
      id: '/_authenticated/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof AuthenticatedRecebimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario-central': {
      id: '/_authenticated/inventario-central'
      path: '/inventario-central'
      fullPath: '/inventario-central'
      preLoaderRoute: typeof AuthenticatedInventarioCentralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracao-meli': {
      id: '/_authenticated/integracao-meli'
      path: '/integracao-meli'
      fullPath: '/integracao-meli'
      preLoaderRoute: typeof AuthenticatedIntegracaoMeliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerencial': {
      id: '/_authenticated/gerencial'
      path: '/gerencial'
      fullPath: '/gerencial'
      preLoaderRoute: typeof AuthenticatedGerencialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devolucoes': {
      id: '/_authenticated/devolucoes'
      path: '/devolucoes'
      fullPath: '/devolucoes'
      preLoaderRoute: typeof AuthenticatedDevolucoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contagem': {
      id: '/_authenticated/contagem'
      path: '/contagem'
      fullPath: '/contagem'
      preLoaderRoute: typeof AuthenticatedContagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bases': {
      id: '/_authenticated/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof AuthenticatedBasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/meli/importar-rota-bruta': {
      id: '/api/public/meli/importar-rota-bruta'
      path: '/api/public/meli/importar-rota-bruta'
      fullPath: '/api/public/meli/importar-rota-bruta'
      preLoaderRoute: typeof ApiPublicMeliImportarRotaBrutaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBasesRoute: typeof AuthenticatedBasesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContagemRoute: typeof AuthenticatedContagemRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevolucoesRoute: typeof AuthenticatedDevolucoesRoute
  AuthenticatedGerencialRoute: typeof AuthenticatedGerencialRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedIntegracaoMeliRoute: typeof AuthenticatedIntegracaoMeliRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedInventarioCentralRoute: typeof AuthenticatedInventarioCentralRoute
  AuthenticatedRecebimentoRoute: typeof AuthenticatedRecebimentoRoute
  AuthenticatedTransferenciasRoute: typeof AuthenticatedTransferenciasRoute
  AuthenticatedTransferenciasLoteRoute: typeof AuthenticatedTransferenciasLoteRoute
  AuthenticatedTriagemRoute: typeof AuthenticatedTriagemRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBasesRoute: AuthenticatedBasesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContagemRoute: AuthenticatedContagemRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevolucoesRoute: AuthenticatedDevolucoesRoute,
  AuthenticatedGerencialRoute: AuthenticatedGerencialRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedIntegracaoMeliRoute: AuthenticatedIntegracaoMeliRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedInventarioCentralRoute: AuthenticatedInventarioCentralRoute,
  AuthenticatedRecebimentoRoute: AuthenticatedRecebimentoRoute,
  AuthenticatedTransferenciasRoute: AuthenticatedTransferenciasRoute,
  AuthenticatedTransferenciasLoteRoute: AuthenticatedTransferenciasLoteRoute,
  AuthenticatedTriagemRoute: AuthenticatedTriagemRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TvRouteChildren {
  TvDashboardRoute: typeof TvDashboardRoute
  TvGerencialRoute: typeof TvGerencialRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvDashboardRoute: TvDashboardRoute,
  TvGerencialRoute: TvGerencialRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PreviewRelatoriosRoute: PreviewRelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TvRoute: TvRouteWithChildren,
  ApiPublicMeliImportarRotaBrutaRoute: ApiPublicMeliImportarRotaBrutaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
