/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PreviewRelatoriosRouteImport } from './routes/preview-relatorios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TvRouteImport } from './routes/tv'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedBasesRouteImport } from './routes/_authenticated/bases'
import { Route as AuthenticatedColetorRouteImport } from './routes/_authenticated/coletor'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContagemRouteImport } from './routes/_authenticated/contagem'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevolucoesRouteImport } from './routes/_authenticated/devolucoes'
import { Route as AuthenticatedGerencialRouteImport } from './routes/_authenticated/gerencial'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedIntegracaoMeliRouteImport } from './routes/_authenticated/integracao-meli'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedInventarioCentralRouteImport } from './routes/_authenticated/inventario-central'
import { Route as AuthenticatedMeliDevolucoesRouteImport } from './routes/_authenticated/meli-devolucoes'
import { Route as AuthenticatedMeliRiscoRouteImport } from './routes/_authenticated/meli-risco'
import { Route as AuthenticatedPainelOperacionalRouteImport } from './routes/_authenticated/painel-operacional'
import { Route as AuthenticatedRecebimentoRouteImport } from './routes/_authenticated/recebimento'
import { Route as AuthenticatedTransferenciasRouteImport } from './routes/_authenticated/transferencias'
import { Route as AuthenticatedTransferenciasLoteRouteImport } from './routes/_authenticated/transferencias-lote'
import { Route as AuthenticatedTriagemRouteImport } from './routes/_authenticated/triagem'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as TvDashboardRouteImport } from './routes/tv.dashboard'
import { Route as TvGerencialRouteImport } from './routes/tv.gerencial'
import { Route as TvMeliRouteImport } from './routes/tv.meli'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiMeliOauthCallbackRouteImport } from './routes/api/meli/oauth/callback'
import { Route as ApiPublicMeliCicloRouteImport } from './routes/api/public/meli/ciclo'
import { Route as ApiPublicMeliImportarRotaBrutaRouteImport } from './routes/api/public/meli/importar-rota-bruta'
import { Route as ApiPublicMeliNotificacoesRouteImport } from './routes/api/public/meli/notificacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRelatoriosRoute = PreviewRelatoriosRouteImport.update({
  id: '/preview-relatorios',
  path: '/preview-relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBasesRoute = AuthenticatedBasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColetorRoute = AuthenticatedColetorRouteImport.update({
  id: '/coletor',
  path: '/coletor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContagemRoute = AuthenticatedContagemRouteImport.update({
  id: '/contagem',
  path: '/contagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevolucoesRoute = AuthenticatedDevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerencialRoute = AuthenticatedGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracaoMeliRoute =
  AuthenticatedIntegracaoMeliRouteImport.update({
    id: '/integracao-meli',
    path: '/integracao-meli',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioCentralRoute =
  AuthenticatedInventarioCentralRouteImport.update({
    id: '/inventario-central',
    path: '/inventario-central',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeliDevolucoesRoute =
  AuthenticatedMeliDevolucoesRouteImport.update({
    id: '/meli-devolucoes',
    path: '/meli-devolucoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeliRiscoRoute = AuthenticatedMeliRiscoRouteImport.update({
  id: '/meli-risco',
  path: '/meli-risco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelOperacionalRoute =
  AuthenticatedPainelOperacionalRouteImport.update({
    id: '/painel-operacional',
    path: '/painel-operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecebimentoRoute =
  AuthenticatedRecebimentoRouteImport.update({
    id: '/recebimento',
    path: '/recebimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransferenciasRoute =
  AuthenticatedTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransferenciasLoteRoute =
  AuthenticatedTransferenciasLoteRouteImport.update({
    id: '/transferencias-lote',
    path: '/transferencias-lote',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTriagemRoute = AuthenticatedTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TvDashboardRoute = TvDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TvRoute,
} as any)
const TvGerencialRoute = TvGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => TvRoute,
} as any)
const TvMeliRoute = TvMeliRouteImport.update({
  id: '/meli',
  path: '/meli',
  getParentRoute: () => TvRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeliOauthCallbackRoute = ApiMeliOauthCallbackRouteImport.update({
  id: '/api/meli/oauth/callback',
  path: '/api/meli/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMeliCicloRoute = ApiPublicMeliCicloRouteImport.update({
  id: '/api/public/meli/ciclo',
  path: '/api/public/meli/ciclo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMeliImportarRotaBrutaRoute =
  ApiPublicMeliImportarRotaBrutaRouteImport.update({
    id: '/api/public/meli/importar-rota-bruta',
    path: '/api/public/meli/importar-rota-bruta',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMeliNotificacoesRoute =
  ApiPublicMeliNotificacoesRouteImport.update({
    id: '/api/public/meli/notificacoes',
    path: '/api/public/meli/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/preview-relatorios': typeof PreviewRelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tv': typeof TvRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/bases': typeof AuthenticatedBasesRoute
  '/coletor': typeof AuthenticatedColetorRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contagem': typeof AuthenticatedContagemRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/gerencial': typeof AuthenticatedGerencialRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/integracao-meli': typeof AuthenticatedIntegracaoMeliRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/inventario-central': typeof AuthenticatedInventarioCentralRoute
  '/meli-devolucoes': typeof AuthenticatedMeliDevolucoesRoute
  '/meli-risco': typeof AuthenticatedMeliRiscoRoute
  '/painel-operacional': typeof AuthenticatedPainelOperacionalRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/transferencias-lote': typeof AuthenticatedTransferenciasLoteRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/tv/dashboard': typeof TvDashboardRoute
  '/tv/gerencial': typeof TvGerencialRoute
  '/tv/meli': typeof TvMeliRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/meli/oauth/callback': typeof ApiMeliOauthCallbackRoute
  '/api/public/meli/ciclo': typeof ApiPublicMeliCicloRoute
  '/api/public/meli/importar-rota-bruta': typeof ApiPublicMeliImportarRotaBrutaRoute
  '/api/public/meli/notificacoes': typeof ApiPublicMeliNotificacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/preview-relatorios': typeof PreviewRelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tv': typeof TvRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/bases': typeof AuthenticatedBasesRoute
  '/coletor': typeof AuthenticatedColetorRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contagem': typeof AuthenticatedContagemRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/gerencial': typeof AuthenticatedGerencialRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/integracao-meli': typeof AuthenticatedIntegracaoMeliRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/inventario-central': typeof AuthenticatedInventarioCentralRoute
  '/meli-devolucoes': typeof AuthenticatedMeliDevolucoesRoute
  '/meli-risco': typeof AuthenticatedMeliRiscoRoute
  '/painel-operacional': typeof AuthenticatedPainelOperacionalRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/transferencias-lote': typeof AuthenticatedTransferenciasLoteRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/tv/dashboard': typeof TvDashboardRoute
  '/tv/gerencial': typeof TvGerencialRoute
  '/tv/meli': typeof TvMeliRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/meli/oauth/callback': typeof ApiMeliOauthCallbackRoute
  '/api/public/meli/ciclo': typeof ApiPublicMeliCicloRoute
  '/api/public/meli/importar-rota-bruta': typeof ApiPublicMeliImportarRotaBrutaRoute
  '/api/public/meli/notificacoes': typeof ApiPublicMeliNotificacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/preview-relatorios': typeof PreviewRelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tv': typeof TvRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/bases': typeof AuthenticatedBasesRoute
  '/_authenticated/coletor': typeof AuthenticatedColetorRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contagem': typeof AuthenticatedContagemRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devolucoes': typeof AuthenticatedDevolucoesRoute
  '/_authenticated/gerencial': typeof AuthenticatedGerencialRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/integracao-meli': typeof AuthenticatedIntegracaoMeliRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/inventario-central': typeof AuthenticatedInventarioCentralRoute
  '/_authenticated/meli-devolucoes': typeof AuthenticatedMeliDevolucoesRoute
  '/_authenticated/meli-risco': typeof AuthenticatedMeliRiscoRoute
  '/_authenticated/painel-operacional': typeof AuthenticatedPainelOperacionalRoute
  '/_authenticated/recebimento': typeof AuthenticatedRecebimentoRoute
  '/_authenticated/transferencias': typeof AuthenticatedTransferenciasRoute
  '/_authenticated/transferencias-lote': typeof AuthenticatedTransferenciasLoteRoute
  '/_authenticated/triagem': typeof AuthenticatedTriagemRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/tv/dashboard': typeof TvDashboardRoute
  '/tv/gerencial': typeof TvGerencialRoute
  '/tv/meli': typeof TvMeliRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/meli/oauth/callback': typeof ApiMeliOauthCallbackRoute
  '/api/public/meli/ciclo': typeof ApiPublicMeliCicloRoute
  '/api/public/meli/importar-rota-bruta': typeof ApiPublicMeliImportarRotaBrutaRoute
  '/api/public/meli/notificacoes': typeof ApiPublicMeliNotificacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/preview-relatorios'
    | '/reset-password'
    | '/tv'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auditoria'
    | '/bases'
    | '/coletor'
    | '/configuracoes'
    | '/contagem'
    | '/dashboard'
    | '/devolucoes'
    | '/gerencial'
    | '/historico'
    | '/integracao-meli'
    | '/inventario'
    | '/inventario-central'
    | '/meli-devolucoes'
    | '/meli-risco'
    | '/painel-operacional'
    | '/recebimento'
    | '/transferencias'
    | '/transferencias-lote'
    | '/triagem'
    | '/usuarios'
    | '/tv/dashboard'
    | '/tv/gerencial'
    | '/tv/meli'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/meli/oauth/callback'
    | '/api/public/meli/ciclo'
    | '/api/public/meli/importar-rota-bruta'
    | '/api/public/meli/notificacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/preview-relatorios'
    | '/reset-password'
    | '/tv'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auditoria'
    | '/bases'
    | '/coletor'
    | '/configuracoes'
    | '/contagem'
    | '/dashboard'
    | '/devolucoes'
    | '/gerencial'
    | '/historico'
    | '/integracao-meli'
    | '/inventario'
    | '/inventario-central'
    | '/meli-devolucoes'
    | '/meli-risco'
    | '/painel-operacional'
    | '/recebimento'
    | '/transferencias'
    | '/transferencias-lote'
    | '/triagem'
    | '/usuarios'
    | '/tv/dashboard'
    | '/tv/gerencial'
    | '/tv/meli'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/meli/oauth/callback'
    | '/api/public/meli/ciclo'
    | '/api/public/meli/importar-rota-bruta'
    | '/api/public/meli/notificacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/preview-relatorios'
    | '/reset-password'
    | '/tv'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/auditoria'
    | '/_authenticated/bases'
    | '/_authenticated/coletor'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contagem'
    | '/_authenticated/dashboard'
    | '/_authenticated/devolucoes'
    | '/_authenticated/gerencial'
    | '/_authenticated/historico'
    | '/_authenticated/integracao-meli'
    | '/_authenticated/inventario'
    | '/_authenticated/inventario-central'
    | '/_authenticated/meli-devolucoes'
    | '/_authenticated/meli-risco'
    | '/_authenticated/painel-operacional'
    | '/_authenticated/recebimento'
    | '/_authenticated/transferencias'
    | '/_authenticated/transferencias-lote'
    | '/_authenticated/triagem'
    | '/_authenticated/usuarios'
    | '/tv/dashboard'
    | '/tv/gerencial'
    | '/tv/meli'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/meli/oauth/callback'
    | '/api/public/meli/ciclo'
    | '/api/public/meli/importar-rota-bruta'
    | '/api/public/meli/notificacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PreviewRelatoriosRoute: typeof PreviewRelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TvRoute: typeof TvRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiMeliOauthCallbackRoute: typeof ApiMeliOauthCallbackRoute
  ApiPublicMeliCicloRoute: typeof ApiPublicMeliCicloRoute
  ApiPublicMeliImportarRotaBrutaRoute: typeof ApiPublicMeliImportarRotaBrutaRoute
  ApiPublicMeliNotificacoesRoute: typeof ApiPublicMeliNotificacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-relatorios': {
      id: '/preview-relatorios'
      path: '/preview-relatorios'
      fullPath: '/preview-relatorios'
      preLoaderRoute: typeof PreviewRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bases': {
      id: '/_authenticated/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof AuthenticatedBasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coletor': {
      id: '/_authenticated/coletor'
      path: '/coletor'
      fullPath: '/coletor'
      preLoaderRoute: typeof AuthenticatedColetorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contagem': {
      id: '/_authenticated/contagem'
      path: '/contagem'
      fullPath: '/contagem'
      preLoaderRoute: typeof AuthenticatedContagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devolucoes': {
      id: '/_authenticated/devolucoes'
      path: '/devolucoes'
      fullPath: '/devolucoes'
      preLoaderRoute: typeof AuthenticatedDevolucoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerencial': {
      id: '/_authenticated/gerencial'
      path: '/gerencial'
      fullPath: '/gerencial'
      preLoaderRoute: typeof AuthenticatedGerencialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracao-meli': {
      id: '/_authenticated/integracao-meli'
      path: '/integracao-meli'
      fullPath: '/integracao-meli'
      preLoaderRoute: typeof AuthenticatedIntegracaoMeliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario-central': {
      id: '/_authenticated/inventario-central'
      path: '/inventario-central'
      fullPath: '/inventario-central'
      preLoaderRoute: typeof AuthenticatedInventarioCentralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meli-devolucoes': {
      id: '/_authenticated/meli-devolucoes'
      path: '/meli-devolucoes'
      fullPath: '/meli-devolucoes'
      preLoaderRoute: typeof AuthenticatedMeliDevolucoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meli-risco': {
      id: '/_authenticated/meli-risco'
      path: '/meli-risco'
      fullPath: '/meli-risco'
      preLoaderRoute: typeof AuthenticatedMeliRiscoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-operacional': {
      id: '/_authenticated/painel-operacional'
      path: '/painel-operacional'
      fullPath: '/painel-operacional'
      preLoaderRoute: typeof AuthenticatedPainelOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recebimento': {
      id: '/_authenticated/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof AuthenticatedRecebimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencias': {
      id: '/_authenticated/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof AuthenticatedTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencias-lote': {
      id: '/_authenticated/transferencias-lote'
      path: '/transferencias-lote'
      fullPath: '/transferencias-lote'
      preLoaderRoute: typeof AuthenticatedTransferenciasLoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/triagem': {
      id: '/_authenticated/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AuthenticatedTriagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tv/dashboard': {
      id: '/tv/dashboard'
      path: '/dashboard'
      fullPath: '/tv/dashboard'
      preLoaderRoute: typeof TvDashboardRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/gerencial': {
      id: '/tv/gerencial'
      path: '/gerencial'
      fullPath: '/tv/gerencial'
      preLoaderRoute: typeof TvGerencialRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/meli': {
      id: '/tv/meli'
      path: '/meli'
      fullPath: '/tv/meli'
      preLoaderRoute: typeof TvMeliRouteImport
      parentRoute: typeof TvRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meli/oauth/callback': {
      id: '/api/meli/oauth/callback'
      path: '/api/meli/oauth/callback'
      fullPath: '/api/meli/oauth/callback'
      preLoaderRoute: typeof ApiMeliOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meli/ciclo': {
      id: '/api/public/meli/ciclo'
      path: '/api/public/meli/ciclo'
      fullPath: '/api/public/meli/ciclo'
      preLoaderRoute: typeof ApiPublicMeliCicloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meli/importar-rota-bruta': {
      id: '/api/public/meli/importar-rota-bruta'
      path: '/api/public/meli/importar-rota-bruta'
      fullPath: '/api/public/meli/importar-rota-bruta'
      preLoaderRoute: typeof ApiPublicMeliImportarRotaBrutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meli/notificacoes': {
      id: '/api/public/meli/notificacoes'
      path: '/api/public/meli/notificacoes'
      fullPath: '/api/public/meli/notificacoes'
      preLoaderRoute: typeof ApiPublicMeliNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBasesRoute: typeof AuthenticatedBasesRoute
  AuthenticatedColetorRoute: typeof AuthenticatedColetorRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContagemRoute: typeof AuthenticatedContagemRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevolucoesRoute: typeof AuthenticatedDevolucoesRoute
  AuthenticatedGerencialRoute: typeof AuthenticatedGerencialRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIntegracaoMeliRoute: typeof AuthenticatedIntegracaoMeliRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedInventarioCentralRoute: typeof AuthenticatedInventarioCentralRoute
  AuthenticatedMeliDevolucoesRoute: typeof AuthenticatedMeliDevolucoesRoute
  AuthenticatedMeliRiscoRoute: typeof AuthenticatedMeliRiscoRoute
  AuthenticatedPainelOperacionalRoute: typeof AuthenticatedPainelOperacionalRoute
  AuthenticatedRecebimentoRoute: typeof AuthenticatedRecebimentoRoute
  AuthenticatedTransferenciasRoute: typeof AuthenticatedTransferenciasRoute
  AuthenticatedTransferenciasLoteRoute: typeof AuthenticatedTransferenciasLoteRoute
  AuthenticatedTriagemRoute: typeof AuthenticatedTriagemRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBasesRoute: AuthenticatedBasesRoute,
  AuthenticatedColetorRoute: AuthenticatedColetorRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContagemRoute: AuthenticatedContagemRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevolucoesRoute: AuthenticatedDevolucoesRoute,
  AuthenticatedGerencialRoute: AuthenticatedGerencialRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIntegracaoMeliRoute: AuthenticatedIntegracaoMeliRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedInventarioCentralRoute: AuthenticatedInventarioCentralRoute,
  AuthenticatedMeliDevolucoesRoute: AuthenticatedMeliDevolucoesRoute,
  AuthenticatedMeliRiscoRoute: AuthenticatedMeliRiscoRoute,
  AuthenticatedPainelOperacionalRoute: AuthenticatedPainelOperacionalRoute,
  AuthenticatedRecebimentoRoute: AuthenticatedRecebimentoRoute,
  AuthenticatedTransferenciasRoute: AuthenticatedTransferenciasRoute,
  AuthenticatedTransferenciasLoteRoute: AuthenticatedTransferenciasLoteRoute,
  AuthenticatedTriagemRoute: AuthenticatedTriagemRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TvRouteChildren {
  TvDashboardRoute: typeof TvDashboardRoute
  TvGerencialRoute: typeof TvGerencialRoute
  TvMeliRoute: typeof TvMeliRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvDashboardRoute: TvDashboardRoute,
  TvGerencialRoute: TvGerencialRoute,
  TvMeliRoute: TvMeliRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PreviewRelatoriosRoute: PreviewRelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TvRoute: TvRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiMeliOauthCallbackRoute: ApiMeliOauthCallbackRoute,
  ApiPublicMeliCicloRoute: ApiPublicMeliCicloRoute,
  ApiPublicMeliImportarRotaBrutaRoute: ApiPublicMeliImportarRotaBrutaRoute,
  ApiPublicMeliNotificacoesRoute: ApiPublicMeliNotificacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
